import { ContentController } from "../../interfaces";

export const AboutController: ContentController =  {
    summary: ['I am a big fan of application <b>performance optimization</b> and reactive programming. I love finding new, better ways to solve technical and business cases.',
        // 'Over the past <b>7 years</b>, I contributed to user-oriented CMS for the healthcare sector, fleet management web and mobile applications tracking vehicles owned by over two thousand organizations, fluid management system dedicated to petrol retailers and buyers, and real estate market micro frontend applications connecting buyers, brokers, and developers.',
        'Over the past <b>7 years</b>, I have worked on a diverse range of <b>user-centric</b> applications across multiple industries. My contributions include developing content management systems (<b>CMS</b>) tailored for the healthcare sector; creating web and mobile applications for fleet management that track thousands of vehicles for over <b>2 000 organizations</b>; designing a fluid management system for petrol retailers and buyers; building <b>micro frontend</b> applications for the real estate market, connecting buyers, brokers, and developers; and developing a suite of web and mobile solutions for managing city water networks, including early <b>leak detection</b> systems.',
        'I love <b>well-designed</b> applications having <b>UX</b> that helps to solve user problems, and well-designed architecture having Developer Experience that helps to avoid future problems.',
        'So far I have <b>Angular</b>, <b>NgRx</b>, <b>RxJs</b>, Nx workspace, React, Storybook, Javascript, Typescript, HTML, CSS, SCSS, and Flutter under my belt. I used to work with Node.js, MongoDB, and Express.js (MEAN stack). I’m still enthusiastically grabbing onto other Frontend frameworks and libraries.']
}
