import type { Metadata } from "next";
import { Inter } from "next/font/google";
//TODO split globals css
import "./globals.css";
import { cookies, headers } from "next/headers";
import Head from "next/head";
import { Theme } from "./types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const cookieStore = await cookies();

  const prefersColorScheme = headerList.get('sec-ch-prefers-color-scheme');
  const themeCookie = cookieStore.get('theme')?.value;

  const theme  = themeCookie || prefersColorScheme || '' as Theme;

  return (
    <html lang="en">
    <Head>
      <link rel="shortcut icon" href="/favicon.ico"/>
    </Head>
    <head>
      <title></title>
    </head>
    {/*suppressHydrationWarning*/}
      <body className={`${inter.className} ${theme}`}>
        {children}
      </body>
    </html>
  );
}
