import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies, headers } from "next/headers";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Theme = 'light' | 'dark' | '';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = headers();
  const cookieStore = cookies();

  const prefersColorScheme = headerList.get('sec-ch-prefers-color-scheme');
  const themeCookie = cookieStore.get('theme')?.value;

  const theme  = themeCookie || prefersColorScheme || '' as Theme;

  return (
    <html lang="en">
    <Head>
      <link rel="shortcut icon" href="/favicon.ico"/>
    </Head>
    <head>
      <title></title>
    </head>
    {/*suppressHydrationWarning*/}
      <body className={`${inter.className} ${theme}`}>
        {children}
      </body>
    </html>
  );
}
