export enum Skill {
    Angular = 'Angular',
    Typescript = 'Typescript',
    NgRx = 'NgRx',
    RxJs = 'RxJs',
    SCSS = 'SCSS',
    Nx = 'Nx Workspace',
    Material = 'Angular Material',
    MapApi = 'Map API',
    Ionic = 'Ionic',
    PrimeNg = 'PrimeNG',
    Flutter = 'Flutter',
    Dart = 'Dart',
    Storybook = 'Storybook',
    React = 'React',
    NodeJs = 'Node.js',
    ExpressJs = 'Express.js',
    MongoDB = 'MongoDB',

    ReactNative = 'React Native',
    Figma = 'Figma',

    Svelte = 'Svelte',
    Solid = 'Solid.js',
    NextJs = 'Next.js',
    Cypress = 'Cypress',
    Playwright = 'Playwright',
}

export const SKILLS_LINKS: Record<Skill, string> = {
    [Skill.Angular]: 'https://angular.dev/',
    [Skill.Typescript]: 'https://www.typescriptlang.org/',
    [Skill.NgRx]: 'https://ngrx.io/',
    [Skill.RxJs]: 'https://rxjs.dev/',
    [Skill.SCSS]: 'https://sass-lang.com/',
    [Skill.Nx]: 'https://nx.dev/',
    [Skill.Material]: 'https://material.angular.io/',
    [Skill.MapApi]: 'https://developers.google.com/maps',
    [Skill.Ionic]: 'https://ionicframework.com/',
    [Skill.PrimeNg]: 'https://primeng.org/',
    [Skill.Flutter]: 'https://flutter.dev/',
    [Skill.Dart]: 'https://dart.dev/',
    [Skill.Storybook]: 'https://storybook.js.org/',
    [Skill.React]: 'https://react.dev/',
    [Skill.NodeJs]: 'https://nodejs.org/en',
    [Skill.ExpressJs]: 'https://expressjs.com/',
    [Skill.MongoDB]: 'https://www.mongodb.com/',
    [Skill.ReactNative]: 'https://reactnative.dev/',
    [Skill.Figma]: 'https://www.figma.com/',
    [Skill.Svelte]: 'https://svelte.dev/',
    [Skill.Solid]: 'https://www.solidjs.com/',
    [Skill.NextJs]: 'https://nextjs.org/',
    [Skill.Cypress]: 'https://www.cypress.io/',
    [Skill.Playwright]: 'https://playwright.dev/',
}
